### ISSUE TITLE
Demo application overlays black font on black background

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#13]
See the red areas

![image](https://github.com/alphanome-ai/sec-parser/assets/45640029/b00ac2b2-2203-4157-ad27-7ca2d5a64d32)

**Comment by INF800** [comment]
This happens because the input to `st.markdown(...)` is always black font text. 

Would suggest disabling the dark theme for the app.

**Comment by Elijas** [comment]
Thanks for reporting it! 

I added 
```
[theme]
base="light"
```
to `.streamlit/config.toml`

Should be fixed now.
