### ISSUE TITLE
Show trailing text during `tree.render()`

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#16]
I was having a look at the output of `tree.render()` and noticed that only the starting text is being printed as shown below.

```
├── TitleElement: Macroeconomic Conditions
│   ├── TextElement: Macroeconomic conditions, including inflation, cha ... 
```

Does the core logic always make sure that the entire text body is captured if the starting text is right? If not, I would suggest printing out the trailing text also as shown below:

```
├── TitleElement: Macroeconomic Conditions
│   ├── TextElement: Macroeconomic conditions, including inflation, cha ... y’s results of operations and financial condition.
```

Would work easily by replacing 

https://github.com/alphanome-ai/sec-parser/blob/0e034add3d96fbea995d7a58dc744917b7f22dae/sec_parser/semantic_tree/semantic_tree.py#L56

with 

```
title = f"{title[:max_line_length]} ... {title[-max_line_length:]}" 
```

**Comment by INF800** [comment]
@Elijas Does the core logic always make sure that the entire text body is captured if the starting text is captured?

**Comment by Elijas** [comment]
@INF800, you're correct in your understanding. The core logic should ideally ensure that the entire text body is captured if the starting text is captured. However, `tree.render()` was primarily designed as a quick check to ensure that the elements are present overall, not as a detailed inspection tool.

For a more detailed inspection, I recommend using the debug dashboard, which can be accessed by running the `task dash` command. This tool makes it much easier to manually investigate the tree and its elements.

Your suggestion to print out the trailing text is valuable and could be a good enhancement for the `tree.render()` function. We appreciate your input and encourage you to contribute to this enhancement if you're interested.

Let me know if this clarifies your question. If not, feel free to rephrase it, and I'll be happy to assist further.
