### ISSUE TITLE
Additional Instructions to add API Key & Developer setup

### ISSUE THREAD

**Issue by Raymondangsetya** [alphanome-ai/sec-parser#18]
Following @INF800 addition towards the readme.md in issue #10, I personally think it will be better if we add .env tutorial to set up the SECAPIO_API_KEY and add these lines of code in the readme.md file.
```
from dotenv import load_dotenv
import os

env_path = ".env"
load_dotenv(dotenv_path=env_path)
api_key = os.environ.get('SECAPIO_API_KEY')
```

By the way, I just noticed that the changes merged regarding the previous issue is r verted eby this commit https://github.com/alphanome-ai/sec-parser/commit/6e2d1a8b883f922263fdb4655647c4548a631e51

**Comment by Elijas** [comment]
Hi @Raymondangsetya,

Great suggestion! 

Since then, we've moved away from sec-api.io to using SEC EDGAR directly, therefore there's no more need to manage the keys 🙌

Thanks again for the suggestion
