### ISSUE TITLE
Caching for .parse_latest

### ISSUE THREAD

**Issue by Raymondangsetya** [alphanome-ai/sec-parser#19]
As noted in the readme.md

**The parser utilizes caching, so multiple calls to retrieve the same data will not consume your API calls limit.**

After running the code several times, I found that the API calls quota is being consumed. I noticed that the .parse_latest() currently doesn't seem to have any caching yet or I am missing something. Can someone help confirming this? 

Thanks

**Comment by Elijas** [comment]
Hi @Raymondangsetya,

Hope you're doing well!

I wanted to take a moment to thank you for your keen observation regarding the `.parse_latest()` function. Your input is invaluable to us and helps us improve our system.

I understand your concern about the API calls quota. However, I'm excited to share that we're currently transitioning away from sec-api.io. This change will essentially make the caching issue a thing of the past, as our new system will handle API calls differently.

We're really looking forward to this transition and the improvements it will bring to our system. We appreciate your understanding and patience during this period.

Please don't hesitate to reach out if you have any more questions or concerns. We're here to help!

Warm Regards, 
Elijas

[Link to the issue](https://github.com/alphanome-ai/sec-parser/issues/9)
