### ISSUE TITLE
small change in doc

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#21]
<img width="540" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/45640029/186665e1-ae82-4de7-b329-0487520de640">

change "blue" in `For example, we can get a percentage of blue text:` to "green".

**Comment by Elijas** [comment]
Yeah, originally it was blue, but it looked too much like a link so I had to change it to another color.

Thanks for spotting this and pushing a PR! 🔥🔥
