### ISSUE TITLE
Dependency issue in`notebooks /developer_guide.ipynb`

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#23]
The notebook will not run on third party jupyter server like colab or binder because `jupyter_black` and `sec_parser` are not installed.

Need to add the below hidden cell:
```
!pip install jupyter-black sec-parser
```

**Comment by Elijas** [comment]
Great catch! 🎯

Thank you for continuing to be a valued member of the community 🎉

Best,
Elijas
