### ISSUE TITLE
ModuleNotFoundError: No module named 'sec_downloader'

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#25]
The import statement for `sec_downloader` in the "How to use" section will not work because instructions for installing `sec_downloader` is not provided. This results in 
```
ModuleNotFoundError: No module named 'sec_downloader'
```

Two ways to handle this:

Either add `pip install sec_downloader` in the README file's "Getting Started" section.

(or)

Add a line with `sec-downloader = "^0.2.3"` in `pyproject.toml`'s `[tool.poetry.dependencies]` instead of just adding it in dev dependencies. This will make sure that the import statement will work with just `pip install sec-ai`

**Comment by Elijas** [comment]
Hey @INF800,

First off, a big thank you for your continuous contributions to `sec-parser`! Your dedication and keen eye for detail are making a real difference to our project. We're really lucky to have you on board.

Now, onto your point about the `ModuleNotFoundError` for `sec_downloader` - you're spot on. We can see how this could be confusing. The `sec_downloader` isn't a hard dependency for `sec-parser`, it's just used in our README as an example. But we totally get that it might seem like it's required.

So, we've gone ahead and updated the README to make this clearer and included instructions for installing `sec_downloader` for anyone who wants to use it. We hope this helps make things a bit more flexible for everyone using `sec-parser`.

Thanks again for bringing this to our attention. Your feedback is always super helpful. If there's anything else you're unsure about or any other suggestions you have, just let us know. We're all ears!

Thanks,
Elijas

**Comment by Elijas** [comment]
Hey @INF800,

I realized that I closed this issue a bit prematurely before checking in with you. I've reopened it to make sure that the updates and clarifications we've made have fully addressed your concerns.

Please let us know if there's anything else we can do to assist you. Your feedback is always welcome!

Best,
Elijas

**Comment by Elijas** [comment]
Hey @INF800,

Quick update: All notebooks are now updated and run end-to-end without any user intervention. Please let us know if everything works as expected on your end.

Best,
Elijas

**Comment by Elijas** [comment]
Hello @INF800,

Since it's been two days without any further issues reported, I'm going to assume that the changes have resolved the installation issue. I'll proceed to close this issue now. 

However, if you encounter any more problems or have any more feedback, please don't hesitate to open a new issue. We appreciate your contributions to improving our project.

Best,
Elijas
