### ISSUE TITLE
Add  "Open in" badge(s) to two jupyter notebooks

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#27]
As discussed in [this thread](https://github.com/orgs/alphanome-ai/discussions/16), we are looking to enhance the accessibility of our guide notebooks by adding an "Open in SageMaker Studio Lab" badge. This badge will allow users to directly open and run the notebooks in a cloud environment, improving the user experience.

## Tasks for Contributors:

1. Update the links in the following badges to point to the guide notebooks (see links below).

    [![Open In SageMaker Studio Lab](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/<PATH_TO_YOUR_NOTEBOOK_ON_GITHUB>)

   [![Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/path_to_the_notebook.ipynb)

2. Verify that clicking the updated link opens the notebook in the cloud environment.

3. Add the updated badge to the following notebooks, positioning it after the existing badges:

    - [Developer Guide Notebook](https://github.com/alphanome-ai/sec-parser/blob/main/docs/source/notebooks/developer_guide.ipynb)
    - [User Guide Notebook](https://github.com/alphanome-ai/sec-parser/blob/main/docs/source/notebooks/user_guide.ipynb)

4. Ensure that the badge functions correctly when integrated into the notebook.

5. Create a GitHub Pull Request with your changes.

---

Special thanks to @mahimairaja for the excellent idea! 🙌 🙌 

This issue is ideal for new contributors, offering a great opportunity to make a significant impact on our project. We appreciate your contributions!

**Comment by mahimairaja** [comment]
Thanks @Elijas 

New contributors, give it a shot!

**Comment by kaustubh-s1** [comment]
Hey @Elijas I'd like to take this up if that's fine :)

**Comment by Elijas** [comment]
Hey there! 👋

Absolutely, we'd be thrilled to have you contribute to this issue. Please feel free to get started on it. If you have any questions or need any assistance, don't hesitate to ask. Looking forward to your pull request!

Thanks, 
Elijas

**Comment by Elijas** [comment]
@kaustubh-s1

Hey there! 👋

Absolutely, we'd be thrilled to have you contribute to this issue. Please feel free to get started on it. If you have any questions or need any assistance, don't hesitate to ask. Looking forward to your pull request!

Thanks,
Elijas

**Comment by Elijas** [comment]
Great work @kaustubh-s1! Your pull request has been merged and the badges have been successfully added to the notebooks. This will greatly improve the accessibility and user experience of our project. 

Thank you for your valuable contribution. We look forward to more of your contributions in the future. 

Closing this issue now as it has been resolved.

Best,
Elijas

**Comment by Elijas** [comment]
<img width="577" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/4084885/42135526-3737-488f-b769-f8e3b393856f">
[source](https://github.com/shroominic/funcchain#demo)

@kaustubh-s1 Do you think we should also add the "Open in Codespaces"?

**Comment by kaustubh-s1** [comment]
That's a good idea @Elijas. It would provide one more easier way to get started with the project 🙌

Should I add it?

**Comment by Elijas** [comment]
Lets continue discussion here
https://github.com/alphanome-ai/sec-parser/issues/58
