### ISSUE TITLE
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_MMM_0000066740-23-000058] - AssertionError: Missing: ['part2item3']

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#30]
Related to #29

---

Currently, `TextElement` can become `HighlightedTextElement` only if 80% of the text content is bold with some font weight. This is not an ideal scenario in cases such as part2item3 of 10-Q_MMM_0000066740-23-000058 which looks like:

<img width="383" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/45640029/9f35dd13-c3b5-4b87-8d23-3e576d4e80ec">

where ~55% of text content is bold with some font weight. The `style_string` default dict for it looks like:

![image](https://github.com/alphanome-ai/sec-parser/assets/45640029/6f5d3d09-d20b-4031-b3a0-6d65daab33f9)

Because of this `TextElement` cannot become `HighlightedTextElement` which in turn cannot become `TitleElement` which in turn cannot become `TopLevelSectionElement`.

### Solution:

Change `PERCENTAGE_THRESHOLD` from `80` to a value less than `54.9`.

https://github.com/alphanome-ai/sec-parser/blob/58304f04f809c00b9b613028a1a961044259556d/sec_parser/semantic_elements/highlighted_text_element.py#L60

In order to find a sweet spot I checked if there were more fails like these where the threshold needs to be decreased, but could not find any in the dataset. So, I think the best value as of now would be `50` percent assuming neither the trailing description or the bold heading has more text content.

**Comment by INF800** [comment]
The affected tests are:
```
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_MMM_0000066740-23-000058] - AssertionError: Missing: ['part2item3']
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_RTX_0000101829-23-000032] - AssertionError: Missing: ['part2item6']
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_TMO_0000097745-23-000059] - AssertionError: Missing: ['part2item6']
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_UPS_0001090727-23-000038] - AssertionError: Missing: ['part2item6']
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_KHC_0001637459-23-000114] - AssertionError: Missing: ['part2item6']
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_MDT_0001613103-23-000128] - AssertionError: Missing: ['part2item6']
```

**Comment by INF800** [comment]
Sweet spot is between `0` and `54.9`.

Upon close inspection, `PERCENTAGE_THRESHOLD=0` helped the following tests pass:
```
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_MMM_0000066740-23-000058] - AssertionError: Missing: ['part2item3']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_RTX_0000101829-23-000032] - AssertionError: Missing: ['part2item6']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_TMO_0000097745-23-000059] - AssertionError: Missing: ['part2item6']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_UPS_0001090727-23-000038] - AssertionError: Missing: ['part2item6']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_KHC_0001637459-23-000114] - AssertionError: Missing: ['part2item6']
```

But created these additional fails:

```
FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_GD_0000040533-23-000060] - AssertionError: 10-Q document should have part1 and part2, but has ['part1', 'part1', 'part2']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_SCHW_0000316709-23-000037] - AssertionError: 10-Q document should have part1 and part2, but has ['part1', 'part1', 'part2']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_MA_0001141391-23-000131] - AssertionError: 10-Q document should have part1 and part2, but has ['part2', 'part2', 'part2']

FAILED tests/generalization/processing_steps/test_top_level_section_title_classifier.py::test_top_level_section_title_classifier[10-Q_GME_0001326380-23-000047] - AssertionError: 10-Q document should have part1 and part2, but has ['part1', 'part1', 'part2']
```

**Comment by INF800** [comment]
Hmm, this change fails at `e2e-varify` with:

```
"10-Q_GOOG_0001652044-23-000070" Line 938 [expected]: "cls_name": "TextElement",
"10-Q_GOOG_0001652044-23-000070" Line 938 [actual]:   "cls_name": "TitleElement",
"10-Q_GOOG_0001652044-23-000070" Line 942 [expected]: "html_hash": "17b63bd7"
"10-Q_GOOG_0001652044-23-000070" Line 942 [actual]:   "html_hash": "17b63bd7",
"10-Q_GOOG_0001652044-23-000070" Line 943 [actual]:   "level": 0
"10-Q_GOOG_0001652044-23-000070" Line 3928 [expected]: "cls_name": "TextElement",
"10-Q_GOOG_0001652044-23-000070" Line 3929 [actual]:   "cls_name": "TitleElement",
"10-Q_GOOG_0001652044-23-000070" Line 3932 [expected]: "html_hash": "9ce67b24"
"10-Q_GOOG_0001652044-23-000070" Line 3933 [actual]:   "html_hash": "9ce67b24",
"10-Q_GOOG_0001652044-23-000070" Line 3934 [actual]:   "level": 0
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                ┃                         ┃      Execution Time      ┃
┃ Report                         ┃        Accuracy         ┃  (Limit, %Limit, Size)   ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10-Q_GOOG_0001652044-23-000070 │ 4 Missing, 6 Unexpected │ 974ms (2095ms, 46%, 2M)  │
│ 10-Q_AAPL_0000320193-23-000077 │            ✓            │ 393ms (963ms, 41%, 963k) │
└────────────────────────────────┴─────────────────────────┴──────────────────────────┘
Note: Execution Time Limit is based on a set rate of 1 microseconds per HTML character (Size).

[ERROR] Verification failed.```

**Comment by Elijas** [comment]
Thanks for creating this issue, it's really on point with what we need right now 🙌 It's always nice to see a high-quality Github Issue, thank you for contributing! 🚀🚀

> So, I think the best value as of now would be 50 percent assuming neither the trailing description or the bold heading has more text content.

But what if the disclaimer message were a little bit longer, then it would break the >50% check 🤔 

I'm thinking, maybe we should have a "failover step", where when the TopLevelSectionTitle couldn't be found the normal way, then scan "TextElements" to be converted to TopLevelSectionTitle. Or maybe even better - pre-split the title into two semantic elements, as "No matters require disclosure" could be its own element?

**Comment by Elijas** [comment]
> Hmm, looks like it affects the general logic. This change fails `e2e-verify` with:
> 
> ```
> "10-Q_GOOG_0001652044-23-000070" Line 938 [expected]: "cls_name": "TextElement",
> "10-Q_GOOG_0001652044-23-000070" Line 938 [actual]:   "cls_name": "TitleElement",
> "10-Q_GOOG_0001652044-23-000070" Line 942 [expected]: "html_hash": "17b63bd7"
> "10-Q_GOOG_0001652044-23-000070" Line 942 [actual]:   "html_hash": "17b63bd7",
> "10-Q_GOOG_0001652044-23-000070" Line 943 [actual]:   "level": 0
> "10-Q_GOOG_0001652044-23-000070" Line 3928 [expected]: "cls_name": "TextElement",
> "10-Q_GOOG_0001652044-23-000070" Line 3929 [actual]:   "cls_name": "TitleElement",
> "10-Q_GOOG_0001652044-23-000070" Line 3932 [expected]: "html_hash": "9ce67b24"
> "10-Q_GOOG_0001652044-23-000070" Line 3933 [actual]:   "html_hash": "9ce67b24",
> "10-Q_GOOG_0001652044-23-000070" Line 3934 [actual]:   "level": 0
> ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓
> ┃                                ┃                         ┃      Execution Time      ┃
> ┃ Report                         ┃        Accuracy         ┃  (Limit, %Limit, Size)   ┃
> ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩
> │ 10-Q_GOOG_0001652044-23-000070 │ 4 Missing, 6 Unexpected │ 974ms (2095ms, 46%, 2M)  │
> │ 10-Q_AAPL_0000320193-23-000077 │            ✓            │ 393ms (963ms, 41%, 963k) │
> └────────────────────────────────┴─────────────────────────┴──────────────────────────┘
> Note: Execution Time Limit is based on a set rate of 1 microseconds per HTML character (Size).
> 
> [ERROR] Verification failed.
> ```

I will quickly mention that failing e2e tests doesn't necessarily mean that it's bad. Sometimes the tests are wrong and need to be updated, for example when we improve the parser output. It's a moving goalpost to make sure we don't regress

**Comment by INF800** [comment]
Sure, thanks!

**Comment by INF800** [comment]
Found a case where un-highlighted text can be a title too.
<img width="824" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/45640029/e35ee8a0-5575-4ca4-a9a0-cac41033f320">

**Comment by Elijas** [comment]
Moved to https://github.com/alphanome-ai/sec-parser/issues/29
