### ISSUE TITLE
`dl.get_latest_html(...)` has hard-coded values

### ISSUE THREAD

**Issue by INF800** [alphanome-ai/sec-parser#33]
It always returns 10-Q docs for AAPL. Fixed and sent PR to it's repo here: https://github.com/Elijas/sec-downloader/pull/2

**Comment by Elijas** [comment]
Good catch 🔥

Merged!

**Comment by Elijas** [comment]
@INF800 Deployed the fix in version `0.2.9`
- If using pip, run `pip install "sec-downloader>=0.2.9"`
- If using poetry, run `poetry update sec-downloader`
