### ISSUE TITLE
Create a visualisation tool that overlays parsed elements with semi-transparent boxes

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#45]
# Background

In the example below, a Semantic Segmentation model consolidates multiple individual pixels into a single, coherent Semantic Element within an image.

![image](https://github.com/alphanome-ai/sec-parser/assets/4084885/1081338f-1495-49b4-851b-9d871160d429)

Similarly, `sec-parser` features a Semantic Segmentation algorithm that consolidates multiple HTML tags into a single, coherent Semantic Element within a page.

# Task

We'd like to have a new python function that has one input (a list of semantic elements) and one output (a string of HTML source code that has all the semi-transparent overlays applied), for example:

<img width="707" alt="Untitled 2" src="https://github.com/alphanome-ai/sec-parser/assets/4084885/abe9212e-58b6-4ecd-afd8-82cca5a4a26a">

The coloring should be based on the type of the semantic element (just an example code to clearly convey the idea).

```
colored_html = ""
for element in parsed_elements:
    if isinstance(element, TextElement): 
        html = element.get_source_code()
        colored_html = colored_html + add_color('yellow', html)
    ...
```

Parsing into a SemanticTree is most likely not needed, you can just use the list of semantic elements.

## Notes 
- You can retrieve the HTML to be modified directly from the semantic elements themselves. Therefore, the input of your function could be just ingesting a list of semantic elements (or a semantic tree).
- It can be either part of the `debug_dashboard` or it can be a completely separate tool in the `dev_utils` folder.

**Comment by kaustubh-s1** [comment]
Hey @Elijas just to confirm before creating a PR-
I made a new file inside `debug_dashboard` and have a function like this-
```py
import sec_parser as sp


def visualize_elements(parsed_elements: list[sp.AbstractSemanticElement]) -> str:
    def add_color(color: str, html: str) -> str:
        return f'<div style="background-color: {color}; opacity: 0.5;">{html}</div>'

    colored_html = ""
    for element in parsed_elements:
        html = element.get_source_code()
        if isinstance(element, sp.TextElement):
            colored_html += add_color('yellow', html)
        elif isinstance(element, sp.TitleElement):
            colored_html += add_color('blue', html)
        elif isinstance(element, sp.TableElement):
            colored_html += add_color('green', html)
        elif isinstance(element, sp.IrrelevantElement):
            colored_html += add_color('red', html)
    return colored_html
```

Can you give some feedback on this and point me in the right direction. 
Otherwise if this looks fine, I can create a PR!

**Comment by kameleon-ad** [comment]
@kaustubh-s1, I'm so sorry for my interrupt. But I don't think it will work.
Especially, in case of the table, it won't work.

**Comment by kaustubh-s1** [comment]
@kameleon-ad can you correct me along with some details?

**Comment by INF800** [comment]
Hello @kaustubh-s1 👋

Did you get a chance to join the Discord group? There is an active discussion on this issue! Discord link is: https://discord.gg/2MC3uJhBxs

**Comment by kaustubh-s1** [comment]
Ohh i see @INF800. Lemme hop in. Thanks

**Comment by Elijas** [comment]
> @kaustubh-s1 Can you give some feedback on this and point me in the right direction? Otherwise, if this looks fine, I can create a PR!

### Request for a demo

Thanks for taking a look at this issue! 🙌 

Could you post a screenshot of how it looks when the HTML is viewed in the browser?


### Code quality
Also, small code changes for efficiency and readability 👍 The original code example was just to convey the logic, sorry if I caused confusion.

1. Consider using a dictionary to relate colors to element types
```python
colors = {
    TextElement: 'yellow',
    ...
}
```
2. Consider using a list, this will be more efficient than continuously appending to a string
```python
colored_html_items = []
... # all the other code here
      colored_html_items.append(html)
... # all the other code here
colored_html = ''.join(colored_html_items)
```


### Link to discussion

Here in discord we talked a bit about the visualization tool in case it's relevant
https://discord.com/channels/1164249739836018698/1164622878147346552/1172238413022376046

**Comment by Elijas** [comment]
We're excited to inform you that @nnilayy is actively working on developing solutions for this PR. If you're interested in collaborating or contributing, we encourage you to reach out for potential collaboration. You can join the discussion on our [**Discord server**](https://discord.gg/2MC3uJhBxs):

<a href="https://discord.gg/2MC3uJhBxs"><img alt="Discord" src="https://img.shields.io/discord/1164249739836018698?logo=discord&logoColor=white&style=flat"></a>

Your input and contributions are highly valued, and we look forward to seeing your ideas and work!

cc @kaustubh-s1

**Comment by kaustubh-s1** [comment]
Sure @Elijas , thanks for notifying on that!
