### ISSUE TITLE
Parse Page Numbers and Page Separators

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#56]
<img width="943" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/4084885/245e088d-14be-4a61-a495-6b834e9fdf0b">

- It would probably be best to create new classes such as `PageElement` which would be inherited from `IrrelevantElement` to allow for an easy removal of all such elements in one swoop
- Include unit tests with a variety of real-life samples. Use pytest test tables. Include the source document ticker and accession number in the test name.

**Comment by fivecctv117** [comment]
@Elijas I would like to work on this issue

**Comment by INF800** [comment]
Hi @fivecctv117, Thank you for showing interest in this issue! Assigning to your user name.

If you have any questions or if we could support you in any way, in addition to using this GitHub issue, feel free to join our [#sec-parser](https://discord.gg/hwdpfxpe) channel to get community support 🙌

**Comment by INF800** [comment]
<img width="832" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/45640029/0b759113-4544-47a5-b69b-bfb78afc58d6">

> [Discord message link](https://discord.com/channels/1164249739836018698/1164646081439744040/1181720582753091695)
