### ISSUE TITLE
Implement "Open in GitHub Codespaces" button in our README

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#58]
Example
<img width="577" alt="image" src="https://github.com/alphanome-ai/sec-parser/assets/4084885/13b22b27-0be1-47e9-842d-bf1a9d162664">
[source](https://github.com/shroominic/funcchain#demo)

- We'll probably need a new repo for that, e.g. repository "sec-parser-examples" with roughly the structure of https://github.com/ricklamers/funcchain-demo
- Let's make it so it contains only the examples in the README.md, as any more advanced examples probably belong in the documentation

**Comment by Elijas** [comment]
Can we (should we) do it without a separate repo? Having it in the dame repo (such as folder /docs/examples/) would allow us to include the example code in the ci/cd pipeline to prevent the example code from breaking (or the outputs from getting outdated)

@kaustubh-s1

**Comment by john0isaac** [comment]
I would like to work on implementing this feature.

**Comment by Elijas** [comment]
@john0isaac Awesome! Let us know if you need anything 🙌
