### ISSUE TITLE
SupplementaryText with repeating text is being identified as IrrelevantElement

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#66]
# Context
[MSFT accuracy-test](https://github.com/alphanome-ai/sec-parser-test-data/blob/main/10-Q/MSFT/0000950170-23-014423/actual-structure-and-text_summary.json) ([permalink](https://github.com/alphanome-ai/sec-parser-test-data/blob/3a3b2616be9569f62d7d1028662fe19ded400601/10-Q/MSFT/0000950170-23-014423/actual-structure-and-text_summary.json) at the time of posting)

**Comment by deenaawny-github-account** [comment]
Hey @Elijas,
I started working on this issue.
For 10-Q MSFT-0000950170-23-014423:
The actual-structure-and-text-summary Json file reports that there are five unexpected SupplementaryText elements. 
```
 "unexpected_elements_by_type": {
            "TopSectionTitle": 10,
            "TitleElement": 18,
            **"SupplementaryText": 5**
        }
```
I looked over all the SupplementaryText elements and they all have the text content "Refer to accompanying notes."
The "SupplementaryTextClassifier" classifies elements that their normalized text expresses the words "accompanying notes" as SupplementaryText elements.
Should I edit the expected-structure-and-text Json file to include them?
I appreciate your feedback.

**Comment by Elijas** [comment]
Just add these manually to `expected-structure-and-text.json` and that will be it 👍

**Comment by deenaawny-github-account** [comment]
Thank you for the feedback.
I added the five missing supplementary text elements in the `expected-structure-and-text.json`.

**Scores**
Previous accuracy scores:
                                                                F1-Score    Recall       Precision     Missing  Unexpected Total
 10-Q_MSFT_0000950170-23-014423    │   94.30% │  97.27% │    91.52% │      10  │         33     │   389

New accuracy scores:
                                                                F1-Score    Recall       Precision     Missing  Unexpected Total
 10-Q_MSFT_0000950170-23-014423    │   95.00% │  97.30% │    92.80% │      10  │         28     │   389

Do I push the changes directly to the main branch of the sec-parser-test-data repository?

I appreciate your feedback.

**Comment by Elijas** [comment]
> Do I push the changes directly to the main branch of the sec-parser-test-data repository?

yes (or create a PR)

**Comment by deenaawny-github-account** [comment]
Pull request: https://github.com/alphanome-ai/sec-parser-test-data/pull/2

**Comment by Elijas** [comment]
Thanks!
