### ISSUE TITLE
The task snapshot-verify fails

### ISSUE THREAD

**Issue by deenaawny-github-account** [alphanome-ai/sec-parser#68]
**Error**
FileNotFoundError: [Errno 2] No such file or directory: '/home/deenaawny/issue-66/sec-parser-test-data/10-Q/AA/0001193125-18-236766/expected-semantic-elements-list.json'
task: Failed to run task "snapshot-verify": exit status 1

**Solution**
comment accession number in selected-filings.yaml

#- 0001193125-18-236766 # 10-Q AA Alcoa Corp 2018-06-30

**Pull Request**
To do

**Comment by Elijas** [comment]
thanks!

just pushed the fix
