### ISSUE TITLE
Manually find bugs in various 10-Q documents and create Github issues

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-parser#7]
# Objective
To enhance sec-parser by manually reviewing 10-Q documents from key companies and addressing issues.

# Process once the Github issues are created:
1. Issue List: Manually review 10-Qs from selected companies and list parsing issues.
1. Triage: Categorize issues as Critical, High, Medium, or Low impact.
1. Plan: Develop a plan to fix these issues.
1. Fix: Start implementing fixes based on priority.

**Comment by Raymondangsetya** [comment]
Hi, I am interested in contributing to your projects, where can I find the list of "selected companies"?

Thanks
