### ISSUE TITLE
Parsers for other type of docs

### ISSUE THREAD

**Issue by jong-inn** [alphanome-ai/sec-parser#80]
Hi, I'm impressed with your work. I'm expecting this work will enable us to extract valuable insights from SEC filings. Really appreciate it.

But I'm wondering if you are planning to add more parsers for other types of documents, such as 10-K, 8-K, etc.
It would be very useful if we have more parsers.

Thanks.

**Comment by Elijas** [comment]
Hi, thanks for reaching out! We're glad you found the parser useful.

The difference from the parser's perspective between 8-K, 10-Q, and 10-K is mainly that they have different top-level sections. Other than that, they're mostly the same and the parser should be able to be used already.

### Option 1

If you don't care about finding the boundaries between top-level sections (or will use other ways to do so), the easiest way to do it would be to use the sec-parser without the `TopSectionManagerFor10Q` processing step.

It could look roughly like this:

```python
from sec_parser import Edgar10QParser, TopSectionManagerFor10Q

class EdgarParserFor10Kand8K(Edgar10QParser):
    def get_default_steps(self):
        steps = super().get_default_steps()
        # Filter out the instance of TopSectionManagerFor10Q from the steps
        return [s for s in steps if not isinstance(s, TopSectionManagerFor10Q)]

html = ... 
parser = EdgarParserFor10Kand8K()
parser.parse(html)
```

### Option 2

To parse top-level section boundaries, a solution could be to add new section titles to
https://github.com/alphanome-ai/sec-parser/blob/main/sec_parser/semantic_elements/top_section_title_types.py
and then create two more classes `Edgar8KParser`, `Edgar10KParser`, each with the respective processing step changed to `TopSectionManagerFor10K` and `TopSectionManagerFor8K`

Let us know if this helps 🙌

**Comment by jong-inn** [comment]
Thanks for the kind reply. I'll definitely try that!

**Comment by Elijas** [comment]
Hey @jong-inn, I have an updated answer, check it out

> [!NOTE]
> For most up to date version of this answer, check out https://github.com/Elijas/sec-parser-exploration/blob/main/02_other_sec_form_types.ipynb

# How do I parse other form types with sec-parser, such as 10-K, 8-K, S-1, etc.?

As of April 2023, sec-parser supports parsing various SEC form types beyond just 10-Q, such as 10-K, 8-K, S-1, and more. Basically, it supports parsing any structured text forms.

However, currently only parsing 10-Q top level section types is supported.

This gives us two methods to parse other form types with sec-parser:

1. Ignore the warnings from the parsing step that identifies the 10-Q top level section types
2. Skip the parsing step that identifies the 10-Q top level section types

# Method 1: Ignore warnings from the parsing step that identifies the 10Q top level section types

```python
import warnings
from sec_downloader import Downloader
import sec_parser as sp

dl = Downloader("MyCompanyName", "email@example.com")
html = dl.get_filing_html(ticker="AAPL", form="10-K")
parser = sp.Edgar10QParser()

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="Invalid section type for")
    elements: list = parser.parse(html)

tree: sp.SemanticTree = sp.TreeBuilder().build(elements)

demo_output_1: str = sp.render(elements)
demo_output_2: str = sp.render(tree)
```

# Method 2: Skip the parsing steps related to the 10Q top level section types

```python
from sec_downloader import Downloader
import sec_parser as sp
from sec_parser.processing_steps import TopSectionManagerFor10Q, IndividualSemanticElementExtractor, TopSectionTitleCheck

dl = Downloader("MyCompanyName", "email@example.com")
html = dl.get_filing_html(ticker="AAPL", form="10-K")

def without_10q_related_steps():
    all_steps = sp.Edgar10QParser().get_default_steps()
    
    # Change 1: Remove the TopSectionManagerFor10Q
    steps_without_top_section_manager = [step for step in all_steps if not isinstance(step, TopSectionManagerFor10Q)]
    
    # Change 2: Replace the IndividualSemanticElementExtractor with a new one that has the top section checks removed
    def get_checks_without_top_section_title_check():
        all_checks = sp.Edgar10QParser().get_default_single_element_checks()
        return [check for check in all_checks if not isinstance(check, TopSectionTitleCheck)]
    return [
        IndividualSemanticElementExtractor(get_checks=get_checks_without_top_section_title_check) 
        if isinstance(step, IndividualSemanticElementExtractor) 
        else step
        for step in steps_without_top_section_manager
    ]

parser = sp.Edgar10QParser(get_steps=without_10q_related_steps)
elements: list = parser.parse(html)
tree: sp.SemanticTree = sp.TreeBuilder().build(elements)

demo_output_1: str = sp.render(elements)
demo_output_2: str = sp.render(tree)
```

# Feedback

Let us know if it helped or if you have any further questions!

Thanks,
Elijas

---
Related: https://github.com/alphanome-ai/sec-parser/issues/81
Related: https://github.com/alphanome-ai/sec-parser/issues/82
