### ISSUE TITLE
Can I get 8K - 10K report?

### ISSUE THREAD

**Issue by joja16** [alphanome-ai/sec-parser#81]
Can I get data of 8K-10K reports? 
If possible, how can I do it?

**Comment by INF800** [comment]
Hi @joja16

Yes, you can get data of 8-K or 10-K report byfollowing the [usage instructions](https://github.com/alphanome-ai/sec-parser?tab=readme-ov-file#usage) in README.md file.

Here are the same code snippets:

```py
from sec_downloader import Downloader

# Initialize the downloader with your company name and email
dl = Downloader("MyCompanyName", "email@example.com")

# Download the latest 10-Q filing for Apple
html1 = dl.get_filing_html(ticker="AAPL", form="10-Q")

# Download the latest 10-K filing for Apple
html2 = dl.get_filing_html(ticker="AAPL", form="8-K")
```

**Comment by Elijas** [comment]
Hey @joja16, thanks for reaching out!

> [!NOTE]
> For most up to date version of this answer, check out https://github.com/Elijas/sec-parser-exploration/blob/main/02_other_sec_form_types.ipynb

# How do I parse other form types with sec-parser, such as 10-K, 8-K, S-1, etc.?

As of April 2023, sec-parser supports parsing various SEC form types beyond just 10-Q, such as 10-K, 8-K, S-1, and more. Basically, it supports parsing any structured text forms.

However, currently only parsing 10-Q top level section types is supported.

This gives us two methods to parse other form types with sec-parser:

1. Ignore the warnings from the parsing step that identifies the 10-Q top level section types
2. Skip the parsing step that identifies the 10-Q top level section types

# Method 1: Ignore warnings from the parsing step that identifies the 10Q top level section types

```python
import warnings
from sec_downloader import Downloader
import sec_parser as sp

dl = Downloader("MyCompanyName", "email@example.com")
html = dl.get_filing_html(ticker="AAPL", form="10-K")
parser = sp.Edgar10QParser()

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="Invalid section type for")
    elements: list = parser.parse(html)

tree: sp.SemanticTree = sp.TreeBuilder().build(elements)

demo_output_1: str = sp.render(elements)
demo_output_2: str = sp.render(tree)
```

# Method 2: Skip the parsing steps related to the 10Q top level section types

```python
from sec_downloader import Downloader
import sec_parser as sp
from sec_parser.processing_steps import TopSectionManagerFor10Q, IndividualSemanticElementExtractor, TopSectionTitleCheck

dl = Downloader("MyCompanyName", "email@example.com")
html = dl.get_filing_html(ticker="AAPL", form="10-K")

def without_10q_related_steps():
    all_steps = sp.Edgar10QParser().get_default_steps()
    
    # Change 1: Remove the TopSectionManagerFor10Q
    steps_without_top_section_manager = [step for step in all_steps if not isinstance(step, TopSectionManagerFor10Q)]
    
    # Change 2: Replace the IndividualSemanticElementExtractor with a new one that has the top section checks removed
    def get_checks_without_top_section_title_check():
        all_checks = sp.Edgar10QParser().get_default_single_element_checks()
        return [check for check in all_checks if not isinstance(check, TopSectionTitleCheck)]
    return [
        IndividualSemanticElementExtractor(get_checks=get_checks_without_top_section_title_check) 
        if isinstance(step, IndividualSemanticElementExtractor) 
        else step
        for step in steps_without_top_section_manager
    ]

parser = sp.Edgar10QParser(get_steps=without_10q_related_steps)
elements: list = parser.parse(html)
tree: sp.SemanticTree = sp.TreeBuilder().build(elements)

demo_output_1: str = sp.render(elements)
demo_output_2: str = sp.render(tree)
```

# Feedback

Let us know if it helped or if you have any further questions!

Thanks,
Elijas

---
Related: https://github.com/alphanome-ai/sec-parser/issues/82
