### ISSUE TITLE
Extracting Text Elements Using sec_parser

### ISSUE THREAD

**Issue by YijingZhang-98** [alphanome-ai/sec-parser#83]
I am currently using sec_parser to parse SEC filings, and I've encountered issues while trying to extract specific text elements such as TopSectionTitle, TitleElement, and TextElement. The output includes ANSI escape codes which seem to interfere with straightforward text extraction.

Is there any subfunction to do this?

**Comment by Elijas** [comment]
Answered on https://github.com/orgs/alphanome-ai/discussions/61
